name: Deploy to OCI

on:
  push:
    branches:
      - master

concurrency:
  cancel-in-progress: true
  group: oci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run deploy script on OCI
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.OCI_HOST }}
          key: ${{ secrets.OCI_KEY }}
          port: 22
          username: ${{ secrets.OCI_USER }}
          script: |
            cd fab-two
            ./deploy.sh
